#!/bin/bash

# Configuration
BINARY_NAME="pmp"
INSTALL_DIR="/usr/local/bin"

# Colors for better readability
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Function to display information message
info() {
    echo -e "${BLUE}[INFO]${NC} $1"
}

# Function to display success message
success() {
    echo -e "${GREEN}[SUCCESS]${NC} $1"
}

# Function to display warning message
warning() {
    echo -e "${YELLOW}[WARNING]${NC} $1"
}

# Function to display error message
error() {
    echo -e "${RED}[ERROR]${NC} $1" >&2
}

# Check if binary exists
info "Searching for $BINARY_NAME installation..."
if [ ! -f "$INSTALL_DIR/$BINARY_NAME" ]; then
    error "$BINARY_NAME is not installed in $INSTALL_DIR."
    exit 1
fi

# Uninstallation confirmation
echo -e "${YELLOW}You are about to uninstall $BINARY_NAME from your system.${NC}"
read -p "Are you sure you want to continue? (y/N) " confirm
if [[ ! "$confirm" =~ ^[yY]([eE][sS])?$ ]]; then
    info "Uninstallation cancelled."
    exit 0
fi

# Remove binary
info "Removing $BINARY_NAME binary..."
if [ -w "$INSTALL_DIR" ]; then
    # If the user has write permissions to the installation directory
    if rm "$INSTALL_DIR/$BINARY_NAME"; then
        success "Binary removed successfully."
    else
        error "Failed to remove binary."
        exit 1
    fi
else
    # If the user doesn't have write permissions, use sudo
    info "Admin rights required to remove $BINARY_NAME from $INSTALL_DIR."
    if command -v sudo >/dev/null 2>&1; then
        if sudo rm "$INSTALL_DIR/$BINARY_NAME"; then
            success "Binary removed successfully."
        else
            error "Failed to remove binary using sudo."
            exit 1
        fi
    else
        error "Unable to remove $BINARY_NAME. You don't have sufficient permissions and sudo is not available."
        exit 1
    fi
fi

# Verify complete removal
if [ -f "$INSTALL_DIR/$BINARY_NAME" ]; then
    warning "Binary still appears to be present in $INSTALL_DIR."
else
    success "Uninstallation complete. $BINARY_NAME has been removed from your system."
fi

# Inform user about data removal
info "Note: Output files generated by $BINARY_NAME in './pmp' folders in your projects have not been removed."

echo -e "\n${GREEN}✅ Uninstallation complete.${NC}"
